---
title: "Plate 3 QC - FEB2026"
output: html_document
date: "2026-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(Seurat)
library(gtools)
library(tidyseurat)
library(Seurat)
library(DESeq2)
library(edgeR)
library(RUVSeq)
library(variancePartition)
library(reshape2)
library(gridExtra)
library(ggrepel)
library(gg.layers)
library(platetools)
library(ggplot2)
library(ggpubr)
library(DT)
```

## Loading data

```{r}
### Importing MACseq data
### Importing metadata
### Joining data in a Seurat object 
source('/Users/dalvinikita/Desktop/macpie/R/filter_genes_by_expression.R')

### import metadata
metadata<-read.csv("/Users/dalvinikita/Documents/13_MACseq_PMMSq057/metadata/PMMSq057_metadata.csv",header=T) %>%
  arrange("Barcode") %>%
  mutate(id=gsub("Plate","",Plate_ID)) %>%
  mutate(Treatment_Combination=paste0(PreTreatment,'_',substr(Treatment_1,1,4))) %>%
  mutate(label=paste0(Treatment_Combination,"_",Well_ID)) %>%
  mutate(Concentration_1=as.factor(Concentration_1)) %>%
  mutate(group = paste0(Treatment_Combination,'.',"SPLINTR"))

row.names(metadata)<-metadata$label

### load in count data 
raw_counts <- Read10X(data.dir = '/Users/dalvinikita/Documents/13_MACseq_PMMSq057/raw/starsolo/')

### filter for the minimum number of reads per gene per sample, as per edgeR
mac <- CreateSeuratObject(counts = raw_counts,
                          project = 'PMMSq057',
                          min.cells = 1,
                          min.features = 0)

mac[["percent.mt"]] <- PercentageFeatureSet(mac, pattern = "^mt-|^MT-")
mac[["percent.ribo"]] <- PercentageFeatureSet(mac, pattern = "^Rp[slp][[:digit:]]|^Rpsa|^RP[SLP][[:digit:]]|^RPSA")

### add location metadata
mac<- mac %>%
  inner_join(metadata,by=c(".cell"="Barcode"))

colnames(mac)<- mac$label

mac <- filter_genes_by_expression(mac,
                                       group_by = "Organoid",
                                       min_counts = 10,
                                       min_samples = 80)

### exclude mito and ribo genes from the counts
mac<-mac[!grepl("^MT-",rownames(mac))]
mac<-mac[!grepl("^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA",rownames(mac))]

### removing ORG60 as not part of chemoresistance experiment
mac_filtered <- mac[,mac$Organoid!='Org60']
mac_filtered <- mac_filtered[,mac_filtered$Treatment_1!='STAUR']

### removing Org60 from metadata 
samples <- colnames(mac_filtered)
metadata_filtered <- metadata[samples,]

```

### Plate QC {.tabset}
```{r}
#facet by Organoid:
grid  <- raw_map(data = mac$nCount_RNA, well = mac$Well_ID, plate = 96) +
  theme_minimal() +
  facet_wrap(~mac$Organoid)+
  scale_fill_viridis_c()

g1 = ggplotGrob(grid)
```

#### Entire plate
```{r}
entire_plate <- raw_map(data = mac$nCount_RNA, well = mac$Well_ID, plate = 384) +
  ggtitle("Entire Plate (PMMSq042)") +
  theme_minimal() +
  scale_fill_viridis_c()

entire_plate
```

### PCA Plots {.tabset}

#### Entire plate
```{r, fig.height=12, fig.width=16, fig.align='left'}

#Function for plotting
pca_plots_plate <- function(df, type){
  if (type=='all'){
    seurat_object <-df %>%
      subset(., Organoid != "NA")
  } else {
    seurat_object <-df %>%
      subset(., Organoid == type)
  }
  
  seurat_object<- seurat_object %>%
    SCTransform(do.scale = T, return.only.var.genes = F, vars.to.regress = "percent.mt",verbose = FALSE) %>%
    FindVariableFeatures(verbose = FALSE) %>%
    RunPCA(npcs = ncol(seurat_object)-1) %>%
    FindNeighbors(verbose = FALSE) %>% 
    FindClusters(method = "igraph", verbose = FALSE)

  p1<-FeaturePlot(seurat_object, features = 'nCount_RNA',pt.size = 2)
  p2<-FeaturePlot(seurat_object, features = 'percent.mt',pt.size = 2)
  p3<-FeaturePlot(seurat_object, features = 'percent.ribo',pt.size = 2)
  p4<-DimPlot(seurat_object, group.by= 'Row',pt.size = 2)
  p5<-DimPlot(seurat_object, group.by= 'Column',pt.size = 2)
  p6<-DimPlot(seurat_object, group.by= 'Organoid',pt.size = 2, shape.by = 'Treatment_1')
  p7<-DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2)
  p8 <- DimPlot(seurat_object, group.by = 'Treatment_1', shape.by = 'Organoid',pt.size = 2)
  p9 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2)
  ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9, nrow=3, ncol=3)
}

pca_plots_plate_dims <- function(df, type){
  if (type=='all'){
    seurat_object <-df %>%
      subset(., Organoid != "NA")
  } else {
    seurat_object <-df %>%
      subset(., Organoid == type)
  }
  
  seurat_object<- seurat_object %>%
    SCTransform(do.scale = T, return.only.var.genes = F, vars.to.regress = "percent.mt",verbose = FALSE) %>%
    FindVariableFeatures(verbose = FALSE) %>%
    RunPCA(npcs = ncol(seurat_object)-1) %>%
    FindNeighbors(verbose = FALSE) %>% 
    FindClusters(method = "igraph", verbose = FALSE)
  
  p1 <- DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2)
  p2 <- DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2, dims=c(3,4))
  p3 <- DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2, dims=c(5,6))
  p4 <- DimPlot(seurat_object, group.by = 'Treatment_1', shape.by = 'Organoid',pt.size = 2)
  p5 <- DimPlot(seurat_object, group.by = 'Treatment_1', shape.by = 'Organoid',pt.size = 2, dims = c(3,4))
  p6 <- DimPlot(seurat_object, group.by = 'Treatment_1', shape.by = 'Organoid',pt.size = 2, dims = c(5,6))
  p7 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2)
  p8 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2, dims = c(3,4))
  p9 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2, dims = c(5,6))
  ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9, nrow=3, ncol=3)
}
pca_plots_plate(mac_filtered, 'all')

pca_plots_plate_dims(mac_filtered, 'all')
```

```{r}
#Function for plotting
pca_plots_org <- function(df, type){
  if (type=='all'){
    seurat_object <-df %>%
      subset(., Organoid != "NA")
  } else {
    seurat_object <-df %>%
      subset(., Organoid == type)
  }
  
  seurat_object<- seurat_object %>%
    SCTransform(do.scale = T, return.only.var.genes = F, vars.to.regress = "percent.mt",verbose = FALSE) %>%
    FindVariableFeatures(verbose = FALSE) %>%
    RunPCA(npcs = ncol(seurat_object)-1) %>%
    FindNeighbors(verbose = FALSE) %>% 
    FindClusters(method = "igraph", verbose = FALSE)

  p1<-FeaturePlot(seurat_object, features = 'nCount_RNA',pt.size = 2)
  p2<-FeaturePlot(seurat_object, features = 'percent.mt',pt.size = 2)
  p3<-FeaturePlot(seurat_object, features = 'percent.ribo',pt.size = 2)
  p4<-DimPlot(seurat_object, group.by= 'Row',pt.size = 2)
  p5<-DimPlot(seurat_object, group.by= 'Column',pt.size = 2)
  p6<-DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2)
  p7<-DimPlot(seurat_object, group.by= 'PreTreatment',pt.size = 2)
  p8 <- DimPlot(seurat_object, group.by = 'Treatment_1', shape.by = 'Concentration_1',pt.size = 2)
  p9 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2)
  ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9, nrow=3, ncol=3)

}

pca_plots_dims <- function(df, type){
  if (type=='all'){
    seurat_object <-df %>%
      subset(., Organoid != "NA")
  } else {
    seurat_object <-df %>%
      subset(., Organoid == type)
  }
  
  seurat_object<- seurat_object %>%
    SCTransform(do.scale = T, return.only.var.genes = F, vars.to.regress = "percent.mt",verbose = FALSE) %>%
    FindVariableFeatures(verbose = FALSE) %>%
    RunPCA(npcs = ncol(seurat_object)-1) %>%
    FindNeighbors(verbose = FALSE) %>% 
    FindClusters(method = "igraph", verbose = FALSE)

  p1<-DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2)
  p2<-DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2, dims=c(3,4))
  p3<-DimPlot(seurat_object, group.by= 'SPLINTR',pt.size = 2, dims=c(5,6))
  p4<-DimPlot(seurat_object, group.by= 'PreTreatment',pt.size = 2)
  p5<-DimPlot(seurat_object, group.by= 'PreTreatment',pt.size = 2, dims=c(3,4))
  p6<-DimPlot(seurat_object, group.by= 'PreTreatment',pt.size = 2, dims=c(5,6))
  p7 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2)
  p8 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2, dims=c(3,4))
  p9 <- DimPlot(seurat_object, group.by = 'Treatment_Combination',pt.size = 2, dims=c(5,6))
  ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9, nrow=3, ncol=3)
}
```

#### ORG38
```{r, fig.height=12, fig.width=16, fig.align='left'}
pca_plots_org(mac_filtered, 'Org38')
pca_plots_dims(mac_filtered, 'Org38')
```

#### ORG49
```{r, fig.height=12, fig.width=16, fig.align='left'}
pca_plots_org(mac_filtered, 'Org49')
pca_plots_dims(mac_filtered, 'Org49')
```


#### ORG66
```{r, fig.height=12, fig.width=16, fig.align='left'}
pca_plots_org(mac_filtered, 'Org66')
pca_plots_dims(mac_filtered, 'Org66')
```
