---
title: "Mac-seq PMC228 QC (VCFG)"
output: html_document
date: "2024-08-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(Seurat)
library(gtools)
library(tidyseurat)
library(Seurat)
library(DESeq2)
library(edgeR)
library(RUVSeq)
library(variancePartition)
library(reshape2)
library(gridExtra)
library(ggrepel)
library(gg.layers)
library(platetools)
library(ggplot2)
library(ggpubr)
```

## Filtering data
```{r, echo=TRUE}
source('/Users/dalvinikita/Desktop/macpie/R/filter_genes_by_expression.R')

#import metadata
metadata<-read.csv("/Volumes/bioinf/home/ndalvi/MACseq_PMC228/metadata/PMC228.csv",header=T, check.names = FALSE) %>%
  arrange("Barcode") %>%
  mutate(id=gsub("Plate","",Plate_ID)) %>%
  mutate(Treatment_conc=paste0(Treatment_1,"_",Concentration_1)) %>%
  mutate(label=paste0(Treatment_1," ","(",Well_ID,")"))

#load in count data 
raw_counts <- Read10X(data.dir = '/Users/dalvinikita/Documents/3_MACseq_PMC228/raw/PMC228/starsolo/SA_PMC228-null.Solo.out/Gene/raw')


row.names(metadata)<-metadata$label

mac <- CreateSeuratObject(counts = raw_counts,
                          project = 'PMC228',
                          min.cells = 1,
                          min.features = 1)

mac[["percent.mt"]] <- PercentageFeatureSet(mac, pattern = "^mt-|^MT-")
mac[["percent.ribo"]] <- PercentageFeatureSet(mac, pattern = "^Rp[slp][[:digit:]]|^Rpsa|^RP[SLP][[:digit:]]|^RPSA")

### add location metadata
mac<- mac %>%
  inner_join(metadata,by=c(".cell"="Barcode"))

mac <- filter_genes_by_expression(mac,
                                       group_by = "Organoid",
                                       min_counts = 10,
                                       min_samples = 80)

### exclude mito and ribo genes from the counts
mac<-mac[!grepl("^MT-",rownames(mac))]
mac<-mac[!grepl("^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA",rownames(mac))]

colnames(mac)<- mac$label
```



### Plate QC {.tabset}
```{r}
#facet by Organoid:
grid  <- raw_map(data = mac$nCount_RNA, well = mac$Well_ID, plate = 384) +
  theme_minimal() +
  facet_wrap(~mac$Organoid)+
  scale_fill_viridis_c()

g1 = ggplotGrob(grid)
```

#### Entire plate
```{r}
entire_plate <- raw_map(data = mac$nCount_RNA, well = mac$Well_ID, plate = 384) +
  ggtitle("Entire Plate (PMC228)") +
  theme_minimal() +
  scale_fill_viridis_c()

entire_plate
```


#### ORG49

```{r}
g1_org49 = g1[-c(9,10),-c(11)]
g1_org49
```

#### ORG38

```{r}
g1_org38 = g1[-c(14,15),-c(7)]
g1_org38
```

#### ORG66

```{r}
g1_org66 = g1[-c(9,10),-c(7)]
g1_org66
```

### PCA Plots {.tabset}

#### Entire plate
```{r, fig.height=12, fig.width=12, fig.align='left'}

#Function for plotting
pca_plots <- function(df, type){
  if (type=='all'){
    seurat_object <-df %>%
      subset(., Cell_type != "")
  } else {
    seurat_object <-df %>%
      subset(., Organoid == type)
  }
  
  seurat_object<- seurat_object %>%
    SCTransform(do.scale = T, return.only.var.genes = F, vars.to.regress = "percent.mt",verbose = FALSE) %>%
    FindVariableFeatures(verbose = FALSE) %>%
    RunPCA(npcs = ncol(seurat_object)-1) %>%
    FindNeighbors(verbose = FALSE) %>% 
    FindClusters(method = "igraph", verbose = FALSE)

  p1<-FeaturePlot(seurat_object, features = 'nCount_RNA',pt.size = 2)
  p2<-FeaturePlot(seurat_object, features = 'percent.mt',pt.size = 2)
  p3<-FeaturePlot(seurat_object, features = 'percent.ribo',pt.size = 2)
  p4<-DimPlot(seurat_object, group.by= 'Row',pt.size = 2)
  p5<-DimPlot(seurat_object, group.by= 'Column',pt.size = 2)
  p6<-DimPlot(seurat_object, group.by= 'Organoid',pt.size = 2)
  p7<-DimPlot(seurat_object, group.by= 'Cell_type',pt.size = 2)
  p8 <- DimPlot(seurat_object, group.by = 'Treatment_1',pt.size = 2)
  p9 <- DimPlot(seurat_object, group.by = 'seurat_clusters',pt.size = 2)
  p10<- DimPlot(seurat_object, group.by= 'Treatment_1',pt.size = 2, dims = c(3,4))
  p11<-DimPlot(seurat_object, group.by= 'Treatment_1',pt.size = 2, dims = c(5,6))
  p12<-DimPlot(seurat_object, group.by= 'Treatment_1',pt.size = 2, dims = c(7,8))
  ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12, nrow=4, ncol=3)
}

p <- pca_plots(mac, 'all')
p

ggsave(p, filename = '/Users/dalvinikita/Documents/7_GitHub/MACseq-SPLINTR-Project/output/P1/P1_QC.png', width = 12, height = 12)
```

#### ORG49
```{r, fig.height=12, fig.width=16, fig.align='left'}

#Function for plotting
pca_plots <- function(df, type){
   if (type=='all'){
    seurat_object <-df %>%
      subset(., Cell_type != "")
  } else {
    seurat_object <-df %>%
      subset(., Organoid == type)
  }
  seurat_object<- seurat_object %>%
    SCTransform(do.scale = T, return.only.var.genes = F, vars.to.regress = "percent.mt",verbose = FALSE) %>%
    FindVariableFeatures(verbose = FALSE) %>%
    RunPCA(npcs = ncol(seurat_object)-1) %>%
    FindNeighbors(verbose = FALSE) %>% 
    FindClusters(method = "igraph", verbose = FALSE)

  p1<-FeaturePlot(seurat_object, features = 'nCount_RNA',pt.size = 2)
  p2<-FeaturePlot(seurat_object, features = 'percent.mt',pt.size = 2)
  p3<-FeaturePlot(seurat_object, features = 'percent.ribo',pt.size = 2)
  p4<-DimPlot(seurat_object, group.by= 'Row',pt.size = 2)
  p5<-DimPlot(seurat_object, group.by= 'Column',pt.size = 2)
  p6<-DimPlot(seurat_object, group.by= 'Time',pt.size = 2)
  p7<-DimPlot(seurat_object, group.by= 'Cell_type',pt.size = 2)
  p8 <- DimPlot(seurat_object, group.by = 'Treatment_1',pt.size = 2)
  p9 <- DimPlot(seurat_object, group.by = 'seurat_clusters',pt.size = 2)
  p10<- DimPlot(seurat_object, group.by= 'Treatment_1',pt.size = 2, dims = c(3,4))
  p11<-DimPlot(seurat_object, group.by= 'Treatment_1',pt.size = 2, dims = c(5,6))
  p12<-DimPlot(seurat_object, group.by= 'Treatment_1',pt.size = 2, dims = c(7,8))
  ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12, nrow=4, ncol=3)
  
  #p10 <- DimPlot(seurat_object, pt.size = 4, group.by = 'Cell_type', split.by='Treatment_1', ncol=4, shape.by = "Time")
  
}

org49_pca <- pca_plots(mac, 'ORG49')
org49_pca

ggsave(org49_pca, filename = '/Users/dalvinikita/Documents/7_GitHub/MACseq-SPLINTR-Project/output/P1/ORG49_QC.png', width = 12, height = 12)
```

#### ORG38
```{r, fig.height=12, fig.width=16, fig.align='left'}
org38_pca <- pca_plots(mac, 'ORG38')
org38_pca

ggsave(org38_pca, filename = '/Users/dalvinikita/Documents/7_GitHub/MACseq-SPLINTR-Project/output/P1/ORG38_QC.png', width = 12, height = 12)
```

#### ORG66
```{r, fig.height=12, fig.width=16, fig.align='left'}
org66_pca <- pca_plots(mac, 'ORG66')
org66_pca

ggsave(org66_pca, filename = '/Users/dalvinikita/Documents/7_GitHub/MACseq-SPLINTR-Project/output/P1/ORG66_QC.png', width = 12, height = 12)
```

### Sample Type Distribution

### Gene Expression


