---
title: "WGCNA Analysis"
output: html_document
date: "2026-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(Seurat)
library(tidyseurat)
library(stringr)
library(WGCNA)
```

## Data {.tabset}

### Plate 1
```{r}
### import metadata
plate1_metadata<-read.csv("/Volumes/bioinf/home/ndalvi/MACseq_PMC228/metadata/PMC228.csv",header=T) %>%
  arrange("Barcode") %>%
  mutate(id=paste0("Plate_1","_",Organoid)) %>%
  mutate(label=paste0("Plate1_",Treatment_1," ","(",Well_ID,")")) %>%
  mutate(interaction_condition=paste0(Drug,".",SPLINTR)) %>%
  mutate(analysis_condition=paste0(Organoid,".",SPLINTR,".",Time))
  

### load in count data 
raw_counts <- Read10X(data.dir = '/Users/dalvinikita/Documents/3_MACseq_PMC228/raw/PMC228/starsolo/SA_PMC228-null.Solo.out/Gene/raw')

### filter for the minimum number of reads per gene per sample, as per edgeR
row.names(plate1_metadata)<-plate1_metadata$label

plate1_expr <- CreateSeuratObject(counts = raw_counts,
                          project = 'PMC228',
                          min.cells = 1,
                          min.features = 1)

plate1_expr[["percent.mt"]] <- PercentageFeatureSet(plate1_expr, pattern = "^mt-|^MT-")
plate1_expr[["percent.ribo"]] <- PercentageFeatureSet(plate1_expr, pattern = "^Rp[slp][[:digit:]]|^Rpsa|^RP[SLP][[:digit:]]|^RPSA")

### add location metadata
plate1_expr<- plate1_expr %>%
  inner_join(plate1_metadata,by=c(".cell"="Barcode"))


colnames(plate1_expr)<- plate1_expr$label

columns_of_interest <- c("id", "Organoid", "Concentration_1", "Treatment_1", "SPLINTR")
```


### Plate 2
```{r}
### import metadata
plate2_metadata<-read.csv("/Users/dalvinikita/Documents/11_MACseq_PMMSq042/PMMSq042.csv",header=T) %>%
  arrange("Barcode") %>%
  mutate(id=paste0("Plate_2","_",Organoid)) %>%
  mutate(Treatment_Combination=paste0(substr(Cell_type,1,2),'_',substr(Treatment_1,1,4))) %>%
  mutate(label=paste0("Plate2_",Treatment_Combination,"_",Well_ID)) %>%
  mutate(Concentration_1=as.factor(Concentration_1)) %>%
  mutate(SPLINTR = str_sub(Cell_type,-1,-1)) %>%
  mutate(group = paste0(Treatment_Combination,'.',SPLINTR)) %>%
  mutate(combined_id = paste0(Cell_type, '_', Treatment_1))


### load in count data 
raw_counts <- Read10X(data.dir = '/Users/dalvinikita/Documents/11_MACseq_PMMSq042/raw')

### filter for the minimum number of reads per gene per sample, as per edgeR
row.names(plate2_metadata)<-plate2_metadata$label

plate2_expr <- CreateSeuratObject(counts = raw_counts,
                          project = 'PMMSq042',
                          min.cells = 1,
                          min.features = 1)

plate2_expr[["percent.mt"]] <- PercentageFeatureSet(plate2_expr, pattern = "^mt-|^MT-")
plate2_expr[["percent.ribo"]] <- PercentageFeatureSet(plate2_expr, pattern = "^Rp[slp][[:digit:]]|^Rpsa|^RP[SLP][[:digit:]]|^RPSA")

### add location metadata
plate2_expr<- plate2_expr %>%
  inner_join(plate2_metadata,by=c(".cell"="Barcode"))


colnames(plate2_expr)<- plate2_expr$label
```

### Plate 3
```{r}
### import metadata
plate3_metadata<-read.csv("/Users/dalvinikita/Documents/13_MACseq_PMMSq057/metadata/PMMSq057_metadata.csv",header=T) %>%
  arrange("Barcode") %>%
    mutate(id=paste0("Plate_3_",Organoid)) %>%
  mutate(Treatment_Combination=paste0(PreTreatment,'_',substr(Treatment_1,1,4))) %>%
  mutate(label=paste0("Plate3_",Treatment_Combination,"_",Well_ID)) %>%
  mutate(Concentration_1=as.factor(Concentration_1)) %>%
  mutate(group = paste0(Treatment_Combination,'.',SPLINTR))

row.names(plate3_metadata)<-plate3_metadata$label

### load in count data 
raw_counts <- Read10X(data.dir = '/Users/dalvinikita/Documents/13_MACseq_PMMSq057/raw/starsolo/')

### filter for the minimum number of reads per gene per sample, as per edgeR
plate3_expr <- CreateSeuratObject(counts = raw_counts,
                          project = 'PMMSq057',
                          min.cells = 1,
                          min.features = 0)

plate3_expr[["percent.mt"]] <- PercentageFeatureSet(plate3_expr, pattern = "^mt-|^MT-")
plate3_expr[["percent.ribo"]] <- PercentageFeatureSet(plate3_expr, pattern = "^Rp[slp][[:digit:]]|^Rpsa|^RP[SLP][[:digit:]]|^RPSA")

### add location metadata
plate3_expr<- plate3_expr %>%
  inner_join(plate3_metadata,by=c(".cell"="Barcode"))

colnames(plate3_expr)<- plate3_expr$label
```

## {-}

```{r}
### joining dataframes together

### Get common genes
common_genes <- Reduce(intersect, list(rownames(plate1_expr),
                                       rownames(plate2_expr),
                                       rownames(plate3_expr)))

# Subset each dataframe
p1_common <- plate1_expr[common_genes, , drop = FALSE]
p2_common <- plate2_expr[common_genes, , drop = FALSE]
p3_common <- plate3_expr[common_genes, , drop = FALSE]

df <- cbind(p1_common@assays$RNA$counts, p2_common@assays$RNA$counts)
df <- cbind(df, p3_common@assays$RNA$counts)

keep <- rowSums(cpm(df) > 10) >= 3

df <- df[keep,]
lcpm <- edgeR::cpm(df, log = TRUE)
# ### combine metadata
# metadata <- rbind(plate1_metadata, plate2_metadata)
# metadata <- rbind(metadata, plate3_metadata)
# rownames(metadata) <- metadata$label
# 
# ### ensure metadata and expr data are ordered in the same way
# sample_order <- colnames(df)
# metadata <- metadata[sample_order,]

input <- t(lcpm)
input <- as.data.frame(input)
```


```{r}
allowWGCNAThreads()
powers = c(c(1:10), seq(from = 12, to = 20, by = 2))
sft = pickSoftThreshold(
  input,             # <= Input data
  blockSize = 10000,
  powerVector = powers,
  verbose = 5
  )
```

```{r}
par(mfrow = c(1,2));
cex1 = 0.9;

plot(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     xlab = "Soft Threshold (power)",
     ylab = "Scale Free Topology Model Fit, signed R^2",
     main = paste("Scale independence")
)
text(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     labels = powers, cex = cex1, col = "red"
)
abline(h = 0.90, col = "red")
plot(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     xlab = "Soft Threshold (power)",
     ylab = "Mean Connectivity",
     type = "n",
     main = paste("Mean connectivity")
)
text(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     labels = powers,
     cex = cex1, col = "red")
```

```{r}
picked_power = 5
temp_cor <- cor       
cor <- WGCNA::cor         # Force it to use WGCNA cor function (fix a namespace conflict issue)
netwk <- blockwiseModules(input,                # <= input here

                          # == Adjacency Function ==
                          power = picked_power,                # <= power here
                          networkType = "signed",

                          # == Tree and Block Options ==
                          deepSplit = 2,
                          pamRespectsDendro = F,
                          # detectCutHeight = 0.75,
                          minModuleSize = 30,
                          maxBlockSize = 4000,

                          # == Module Adjustments ==
                          reassignThreshold = 0,
                          mergeCutHeight = 0.25,

                          # == TOM == Archive the run results in TOM file (saves time)
                          saveTOMs = T,
                          saveTOMFileBase = "ER",

                          # == Output Options
                          numericLabels = T,
                          verbose = 3)
cor <- temp_cor
```
```{r}
# Convert labels to colors for plotting
mergedColors = labels2colors(netwk$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(
  netwk$dendrograms[[1]],
  mergedColors[netwk$blockGenes[[1]]],
  "Module colors",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05 )
```

```{r}
# Get Module Eigengenes per cluster
MEs0 <- moduleEigengenes(input, mergedColors)$eigengenes

# Reorder modules so similar modules are next to each other
MEs0 <- orderMEs(MEs0)
module_order = names(MEs0) %>% gsub("ME","", .)

# Add treatment names
MEs0$treatment = row.names(MEs0)

# tidy & plot data
mME = MEs0 %>%
  pivot_longer(-treatment) %>%
  mutate(
    name = gsub("ME", "", name),
    name = factor(name, levels = module_order)
  )

mME %>% ggplot2::ggplot(., aes(x=treatment, y=name, fill=value)) +
  geom_tile() +
  theme_bw() +
  scale_fill_gradient2(
    low = "red",
    mid = "white",
    high = "#253494",
    midpoint = 0,
    limit = c(-1,1)) +
  theme(axis.text.x = element_text(angle=90)) +
  labs(title = "Module-trait Relationships", y = "Modules", fill="corr")

```
```{r}
seurat_obj <- hdWGCNA::SetupForWGCNA(
  mac_filtered,
  gene_select = "fraction", # the gene selection approach
  fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
  wgcna_name = "tutorial" # the name of the hdWGCNA experiment
)

```
